name: Release

on:
  workflow_dispatch:
    inputs:
      disable_release:
        description: "Disable marketplace publish"
        required: false
        default: true
        type: boolean
      pre_release:
        description: "Pre-release"
        required: false
        default: false
        type: boolean

jobs:
  release_commit:
    permissions:
      contents: write
    if: github.ref_type == 'branch' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Git config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Install convco
        run: |
          curl -OL https://github.com/convco/convco/releases/latest/download/convco-deb.zip
          unzip convco-deb.zip
          sudo dpkg -i convco*.deb
          rm convco*.deb convco-deb.zip
      - name: Create changelog
        run: convco changelog -u $(convco version --bump) -o CHANGELOG.md
      - name: Bump npm version
        run: npm version $(convco version --bump) --no-git-tag-version
      - name: Commit and tag
        run: |
          git config -l
          git add .
          git commit -m "chore(release): v$(convco version --bump)"
          git tag "v$(convco version --bump)"
      - name: Push changes
        run: |
          git push origin HEAD:${{ github.ref_name }}
          git push origin --tags

  build_and_release:
    runs-on: ubuntu-latest
    needs:
      - release_commit
    steps:
      - uses: actions/checkout@v4
      - run: git pull
      - uses: actions/setup-node@v4
        with:
          node-version: "node"
      - run: npm install -g @vscode/vsce
      - run: npm install
      - run: vsce package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension
          path: "*.vsix"
      - name: Publish on marketplace
        if: github.event.inputs.disable_release == 'false' && github.event.inputs.pre_release == 'false'
        run: vsce publish -p ${{ secrets.PAT_MARKETPLACE }}
      - name: Publish on marketplace as pre-release
        if: github.event.inputs.disable_release == 'false' && github.event.inputs.pre_release == 'true'
        run: vsce publish -p ${{ secrets.PAT_MARKETPLACE }} --pre-release

  create_github_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build_and_release
    steps:
      - uses: actions/checkout@v4
      - run: git pull
      - name: Install convco
        run: |
          curl -OL https://github.com/convco/convco/releases/latest/download/convco-deb.zip
          unzip convco-deb.zip
          sudo dpkg -i convco*.deb
          rm convco*.deb convco-deb.zip
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vscode-extension
      - name: Create release changelog
        run: convco changelog -m 1 -o RELEASE_CHANGELOG.md
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v$(convco version) -F RELEASE_CHANGELOG.md -t "v$(convco version)" -R ${{ github.repository }} *.vsix
